import { useEffect, useState } from "react";
import { Button, InlineLoading, InlineNotification, TextArea, TextInput, Toggle } from "@carbon/react";
import { api } from "./api";
import type { NodeCatalogItem } from "./types";
import { parseObject, pretty, Status } from "./ui";

export default function NodeManagement() {
  const [nodes, setNodes] = useState<NodeCatalogItem[]>([]), [selected, setSelected] = useState<NodeCatalogItem>(), [error, setError] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const [name, setName] = useState(""), [description, setDescription] = useState(""), [enabled, setEnabled] = useState(true), [config, setConfig] = useState("{}"), [inputs, setInputs] = useState("{}"), [fixture, setFixture] = useState("{}");
  const choose = (node: NodeCatalogItem) => { const ui = node.uiSchema || {}; setSelected(node); setName(node.name); setDescription(node.description); setEnabled(node.studioEnabled !== false); setConfig(pretty(ui.debugConfig || {})); setInputs(pretty(ui.debugInputs || {})); setFixture(pretty(ui.debugFixture || {})); setError(""); setMessage(""); };
  const load = async () => { try { const value = await api.studioNodes(); setNodes(value.items); if (!selected && value.items[0]) choose(value.items[0]); } catch (value) { setError((value as Error).message); } };
  useEffect(() => { void load(); }, []);
  const save = async () => { if (!selected) return; setBusy(true); setError(""); setMessage(""); try { await api.updateStudioNode(selected.type, selected.schemaVersion, { enabled, name, description, debugConfig: parseObject(config, "默认配置"), debugInputs: parseObject(inputs, "默认输入"), debugFixture: parseObject(fixture, "模拟输出") }); setMessage("Node Studio配置已保存；Handler和Schema保持代码版本不变。"); await load(); } catch (value) { setError((value as Error).message); } finally { setBusy(false); } };
  return <main className="page node-management"><header className="page-title"><div><p className="overline">NODE CATALOG ADMINISTRATION</p><h1>Node管理</h1><p>管理已注册节点在Studio中的启停、名称、说明和调试默认值。执行代码、Schema和风险级别不可在页面修改。</p></div></header>{error && <InlineNotification kind="error" title="Node管理失败" subtitle={error} hideCloseButton />}{message && <InlineNotification kind="success" title="保存成功" subtitle={message} hideCloseButton />}<div className="node-admin-grid"><aside className="node-admin-list"><header><b>Registry Nodes</b><span>{nodes.length}</span></header>{nodes.map((node) => <button type="button" className={selected?.type === node.type ? "active" : ""} key={`${node.type}-${node.schemaVersion}`} onClick={() => choose(node)}><span><b>{node.name}</b><Status value={node.studioEnabled === false ? "DISABLED" : "ENABLED"} /></span><small>{node.type} · schema {node.schemaVersion} · handler {node.handlerVersion}</small></button>)}</aside><section className="node-admin-editor">{selected ? <><header><div><p className="overline">{selected.category} / {selected.type}</p><h2>{selected.name}</h2></div><code>{selected.riskLevel} · {selected.approvalPolicy}</code></header><div className="immutable-strip"><b>不可变执行契约</b><span>Schema v{selected.schemaVersion}</span><span>Handler {selected.handlerVersion}</span><span>{selected.idempotencyClass}</span></div><Toggle id="node-enabled" labelText="允许在Studio编排和调试" toggled={enabled} onToggle={setEnabled} /><TextInput id="node-name" labelText="显示名称" value={name} onChange={(event) => setName(event.target.value)} /><TextArea id="node-description" labelText="使用说明" rows={3} value={description} onChange={(event) => setDescription(event.target.value)} /><div className="node-default-grid"><TextArea id="node-config" labelText="默认节点配置 JSON" rows={12} value={config} onChange={(event) => setConfig(event.target.value)} /><TextArea id="node-inputs" labelText="默认真实调试输入 JSON" rows={12} value={inputs} onChange={(event) => setInputs(event.target.value)} /><TextArea id="node-fixture" labelText="契约测试固定输出 JSON（不用于真实调试）" rows={12} value={fixture} onChange={(event) => setFixture(event.target.value)} /></div><div className="studio-actions"><span>修改仅影响TEST_ONLY Studio，不改变tec01已发布Catalog快照</span><Button onClick={save} disabled={busy}>{busy ? "正在保存" : "保存Node配置"}</Button></div></> : <InlineLoading description="加载Node Registry" />}</section></div></main>;
}
